### ISSUE TITLE
Why consumer is key=string, value=string?

### ISSUE THREAD

**Issue by vasily-kirichenko** [jet/Jet.ConfluentKafka.FSharp#26]

**Comment by bartelink** [comment]
Are you referring to the `v1` or `v0` branches?

Assuming v1; that is as it is because it's extracted from a running system which centered on `Confluent.Kafka` v `0.11.4` and a serializer (Json.net IIRC) that works off a string rendering (and typically keys map to stream names in upstream event-based storage systems).

Happy to take PRs to generalize (with tests please if it's an interesting change to any degree but I'm assuming you're just talking about removing some hard-coding).

**Comment by bartelink** [comment]
Closing for age
